version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-stretch-node
    steps:
      - checkout

      # Bundle dependencies
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Yarn dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Build and test
      - run: rake --trace
